### ISSUE TITLE
Set up Travis to build this and re-link PX4 docs to it

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/FlightPlot#1]
@bkueng @AndreasAntener Could you look into setting up Travis for this and update the PX4 website to point to the resulting binaries? Flight plot is not very actively maintained and it starts to slow us down. We need to have control over the binaries we depend on.

**Comment by AndreasAntener** [comment]
Antons version is already automatically built on creation of a release tag, uploaded to S3 and linked on the old doc: https://pixhawk.org/dev/flightplot#download, http://ec2.antener.name/

I could move that to SITL01

**Comment by AndreasAntener** [comment]
But, I have nothing against it if someone does this with Travis ;). It would be more dev friendly than Jenkins (configuration in github etc..)

**Comment by bkueng** [comment]
@AndreasAntener can you please change the doc & S3 links to point to this repo instead of DrTon's? And make sure the new version gets published? @DrTon agreed to move the main repo over here, because he currently has no time maintaining it.

**Comment by AndreasAntener** [comment]
ok, I'll move it to SITL01 and PX4 S3

**Comment by AndreasAntener** [comment]
@LorenzMeier I added a new bucket `flightplot` in your S3, could you add an access policy and get me the access and secret key for it?

**Comment by LorenzMeier** [comment]
@AndreasAntener You should have full permissions for that, right?

**Comment by AndreasAntener** [comment]
Looks like I do now :)

**Comment by AndreasAntener** [comment]
Could someone add me as admin to the project so I can set the hooks?

or set:
http://sitl01.dronetest.io/github-webhook/ (push)
http://sitl01.dronetest.io/ghprbhook/ (issue_comment and pull_request)

**Comment by LorenzMeier** [comment]
I've given you the permissions.

**Comment by AndreasAntener** [comment]
@LorenzMeier @bkueng it should now work. If you push a tag, the latest tagged version would be available here: https://s3.amazonaws.com/flightplot/releases/latest.html we just need to include that somewhere. Of course the HTML can be modified (it's in the Jenkins job config).

**Comment by bkueng** [comment]
Thanks Andreas. I updated the dev-guide in https://github.com/PX4/Devguide/pull/57.
https://pixhawk.org/dev/flightplot should be updated as well (I don't have access there).

**Comment by AndreasAntener** [comment]
Yeah the old page is locked.. we should remove it if all the infos are in the new guide.
