### ISSUE TITLE
Euler angles are not displayed

### ISSUE THREAD

**Issue by bigbellmercy** [PX4/FlightPlot#21]
Hi, Thanks for FlightPlot.
Euler angles are not displayed in recent version.
Instead, quaternion is displayed but it is difficult to understand attitude change.
So in FlightPlot please make some attitude representation support function.

Environment:
By Pixhawk2.1, px4 v1.7.3 and FlightPlot v0.3.2

**Comment by bkueng** [comment]
There's a conversion: in the fields list, select all 4 quaterion indexes, then `Add`, then select `EulerFromQuaterion` and `Ok`.
