### ISSUE TITLE
Any link for windows download is broken

### ISSUE THREAD

**Issue by tuloski** [PX4/FlightPlot#22]
As title.

**Comment by bkueng** [comment]
Thanks, I fixed it in https://github.com/PX4/FlightPlot/commit/9a73d905e563119ba5316a539f0c2e5f89319fad.

**Comment by tuloski** [comment]
But even at that link which are the windows executable?

**Comment by bkueng** [comment]
It's the jar file: https://github.com/PX4/FlightPlot/releases/download/0.3.2/flightplot.jar.zip
