### ISSUE TITLE
Two different EulerFromQuaternion sources not viewable at the same time

### ISSUE THREAD

**Issue by MaEtUgR** [PX4/FlightPlot#9]
I opened a ulog, chose the set of variables
`control_state_0.q[0] control_state_0.q[1] control_state_0.q[2] control_state_0.q[3]`
with `EulerFromQuaternion` processor and did the same for
`vehicle_attitude_setpoint_0.q_d[0] vehicle_attitude_setpoint_0.q_d[1] vehicle_attitude_setpoint_0.q_d[2] vehicle_attitude_setpoint_0.q_d[3]`.

The result is they newer get displayed at the same time. If both are enabled to view (with the checkboxes) I see either only the first set or the data of the first set in the colors of the second. If only one is displayed it works as expected.

**Comment by kd0aij** [comment]
I do that frequently comparing attitude to attitude setpoint: 
![euler_from_quat_2](https://cloud.githubusercontent.com/assets/2300221/23126610/be90b1e0-f734-11e6-9989-c57438269956.png)
and haven't noticed any problems. What's confusing you is probably that control_state_q is identical to attitude setpoint. Turn on markers and you should be able to see that.

**Comment by MaEtUgR** [comment]
I knew I must have done something wrong... Thanks for the screenshot!
I realized you gave the two sets unique titles by hand.
I didn't do such a nice setup and just kept the default title "New" that's also default the second time. And if you have both datasets with the same title exactly my problem occurs.

- For usability one could consider catching two times the same title and/or suggesting "New1" when the default title is already in use.

My original issue does not exist.
